init:
  - ps: echo $env:TOXENV

cache:
  - '%LOCALAPPDATA%\pip\Cache'

clone_depth: 5

environment:
  fast_finish: true
  matrix:
    - TOXENV: 'py27'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'
    
    - TOXENV: 'py34'
      TOXPYTHON: C:\Python34\python.exe
      PYTHON_HOME: C:\Python34
      PYTHON_VERSION: '3.4'
      PYTHON_ARCH: '32'
    
    - TOXENV: 'py35'
      TOXPYTHON: C:\Python35\python.exe
      PYTHON_HOME: C:\Python35
      PYTHON_VERSION: '3.5'
      PYTHON_ARCH: '32'

    - TOXENV: 'py36'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'
    
    - TOXENV: 'py37'
      TOXPYTHON: C:\Python37\python.exe
      PYTHON_HOME: C:\Python37
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '32'

    - TOXENV: 'lint'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'

matrix:
  fast_finish: true

install:
  - '%PYTHON_HOME%\Scripts\pip --version'
  - '%PYTHON_HOME%\Scripts\pip install tox'
  - '%PYTHON_HOME%\Scripts\tox --version'
  - '%PYTHON_HOME%\Scripts\virtualenv --version'

build: off

test_script:
  - '%PYTHON_HOME%\Scripts\tox -e %TOXENV%'
